package com.aihangxunxi.aitalk.storage.constant;

/**
 * @author chenqingze107@163.com
 * @version 2.0
 */
public enum NotificationType {

	UNDEFINED, INVITE_MEMBER, KICK_MEMBER, LEAVE_TEAM, UPDATE_TEAM, DISMISS_TEAM, PASS_TEAM_APPLY, TRANSFER_OWNER, ADD_TEAM_MANAGER, REMOVE_TEAM_MANAGER, ACCEPT_INVITE, MUTE_TEAM_MEMBER, CHAT_ROOM_MEMBER_IN, CHAT_ROOM_MEMBER_EXIT, CHAT_ROOM_MEMBER_BLACK_ADD, CHAT_ROOM_MEMBER_BLACK_REMOVE, CHAT_ROOM_MEMBER_MUTE_ADD, CHAT_ROOM_MEMBER_MUTE_REMOVE, CHAT_ROOM_MANAGER_ADD, CHAT_ROOM_MANAGER_REMOVE, CHAT_ROOM_COMMON_ADD, CHAT_ROOM_COMMON_REMOVE, CHAT_ROOM_CLOSE, CHAT_ROOM_INFO_UPDATED, CHAT_ROOM_MEMBER_KICKED, CHAT_ROOM_MEMBER_TEMP_MUTE_ADD, CHAT_ROOM_MEMBER_TEMP_MUTE_REMOVE, CHAT_ROOM_MY_ROOM_ROLE_UPDATED, CHAT_ROOM_QUEUE_CHANGE, CHAT_ROOM_ROOM_MUTED, CHAT_ROOM_ROOM_DE_MUTED, CHAT_ROOM_QUEUE_BATCH_CHANGE, SUPER_TEAM_INVITE, SUPER_TEAM_KICK, SUPER_TEAM_LEAVE, SUPER_TEAM_UPDATE_T_INFO, SUPER_TEAM_DISMISS, SUPER_TEAM_CHANGE_OWNER, SUPER_TEAM_ADD_MANAGER, SUPER_TEAM_REMOVE_MANAGER, SUPER_TEAM_MUTE_TLIST, SUPER_TEAM_APPLY_PASS, SUPER_TEAM_INVITE_ACCEPT;

}
